// <auto-generated />
using System;
using MetaFlow.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MetaFlow.API.Migrations
{
    [DbContext(typeof(MetaFlowDbContext))]
    [Migration("20251112170356_InitialCreateOracleFinal")]
    partial class InitialCreateOracleFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MetaFlow.API.Models.Meta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<int>("Categoria")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CATEGORIA");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRIADO_EM")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<DateTime>("Prazo")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PRAZO");

                    b.Property<decimal>("Progresso")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("PROGRESSO");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TITULO");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("Categoria")
                        .HasDatabaseName("IX_METAS_CATEGORIA");

                    b.HasIndex("Prazo")
                        .HasDatabaseName("IX_METAS_PRAZO");

                    b.HasIndex("UsuarioId", "Status")
                        .HasDatabaseName("IX_METAS_USUARIO_STATUS");

                    b.ToTable("METAS", (string)null);
                });

            modelBuilder.Entity("MetaFlow.API.Models.RegistroDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<string>("Anotacoes")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("ANOTACOES");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRIADO_EM")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA");

                    b.Property<int>("Humor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("HUMOR");

                    b.Property<byte>("Produtividade")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("PRODUTIVIDADE");

                    b.Property<short>("TempoFoco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(5)")
                        .HasDefaultValue((short)0)
                        .HasColumnName("TEMPO_FOCO");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("Data")
                        .HasDatabaseName("IX_REGISTROS_DATA");

                    b.HasIndex("UsuarioId", "Data")
                        .IsUnique()
                        .HasDatabaseName("IX_REGISTROS_USUARIO_DATA");

                    b.ToTable("REGISTROS_DIARIOS", (string)null);
                });

            modelBuilder.Entity("MetaFlow.API.Models.ResumoMensal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<byte>("Ano")
                        .HasColumnType("NUMBER(4)")
                        .HasColumnName("ANO");

                    b.Property<DateTime>("CalculadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CALCULADO_EM")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<decimal>("MediaHumor")
                        .HasColumnType("NUMBER(4,2)")
                        .HasColumnName("MEDIA_HUMOR");

                    b.Property<decimal>("MediaProdutividade")
                        .HasColumnType("NUMBER(4,2)")
                        .HasColumnName("MEDIA_PRODUTIVIDADE");

                    b.Property<byte>("Mes")
                        .HasColumnType("NUMBER(2)")
                        .HasColumnName("MES");

                    b.Property<int>("MetasConcluidas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("METAS_CONCLUIDAS");

                    b.Property<decimal>("TaxaConclusao")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("TAXA_CONCLUSAO");

                    b.Property<int>("TotalRegistros")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TOTAL_REGISTROS");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Ano", "Mes")
                        .IsUnique()
                        .HasDatabaseName("IX_RESUMOS_USUARIO_PERIODO");

                    b.ToTable("RESUMOS_MENSAIS", (string)null);
                });

            modelBuilder.Entity("MetaFlow.API.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ATUALIZADO_EM")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRIADO_EM")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("ObjetivoProfissional")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("OBJETIVO_PROFISSIONAL");

                    b.Property<string>("Profissao")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("PROFISSAO");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("SENHA_HASH");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_USUARIOS_EMAIL");

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("MetaFlow.API.Models.Meta", b =>
                {
                    b.HasOne("MetaFlow.API.Models.Usuario", "Usuario")
                        .WithMany("Metas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_METAS_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MetaFlow.API.Models.RegistroDiario", b =>
                {
                    b.HasOne("MetaFlow.API.Models.Usuario", "Usuario")
                        .WithMany("RegistrosDiarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_REGISTROS_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MetaFlow.API.Models.ResumoMensal", b =>
                {
                    b.HasOne("MetaFlow.API.Models.Usuario", "Usuario")
                        .WithMany("ResumosMensais")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RESUMOS_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MetaFlow.API.Models.Usuario", b =>
                {
                    b.Navigation("Metas");

                    b.Navigation("RegistrosDiarios");

                    b.Navigation("ResumosMensais");
                });
#pragma warning restore 612, 618
        }
    }
}
